//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPSProfessional.SharePoint.Framework.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SPSProfessional_SharePoint_Framework {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SPSProfessional_SharePoint_Framework() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPSProfessional.SharePoint.Framework.Resources.SPSProfessional.SharePoint.Framewo" +
                            "rk", typeof(SPSProfessional_SharePoint_Framework).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable open site &apos;{0}&apos; please check URL in web.config under appSettings/{1}..
        /// </summary>
        internal static string SPSCM_Err_InvalidUrlInWebContext {
            get {
                return ResourceManager.GetString("SPSCM_Err_InvalidUrlInWebContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No config item was found for category &apos;{0}&apos; and key &apos;{1}&apos;..
        /// </summary>
        internal static string SPSCM_Err_KeyNotFound {
            get {
                return ResourceManager.GetString("SPSCM_Err_KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find configuration list with name &apos;{0}&apos;..
        /// </summary>
        internal static string SPSCM_Err_ListNotFound {
            get {
                return ResourceManager.GetString("SPSCM_Err_ListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find key for SPS Configuration Manager in web.config under appSettings/{0}..
        /// </summary>
        internal static string SPSCM_Err_OutContextWebConfig {
            get {
                return ResourceManager.GetString("SPSCM_Err_OutContextWebConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration web not found in site collection {0}..
        /// </summary>
        internal static string SPSCM_Err_WebNotFound {
            get {
                return ResourceManager.GetString("SPSCM_Err_WebNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache Settings.
        /// </summary>
        internal static string SPSFW_CacheEditorPartTitle {
            get {
                return ResourceManager.GetString("SPSFW_CacheEditorPartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache time in seconds:.
        /// </summary>
        internal static string SPSFW_CacheTimeOut {
            get {
                return ResourceManager.GetString("SPSFW_CacheTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Cache.
        /// </summary>
        internal static string SPSFW_EnableCache {
            get {
                return ResourceManager.GetString("SPSFW_EnableCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the license file..
        /// </summary>
        internal static string SPSFW_Err_CheckLicenseFile {
            get {
                return ResourceManager.GetString("SPSFW_Err_CheckLicenseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check webpart properties in tool panel..
        /// </summary>
        internal static string SPSFW_Err_CheckWebPartProperties {
            get {
                return ResourceManager.GetString("SPSFW_Err_CheckWebPartProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid XML for Calendar.
        /// </summary>
        internal static string SPSFW_Err_XmlCalendar {
            get {
                return ResourceManager.GetString("SPSFW_Err_XmlCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xslt Transformation Error.
        /// </summary>
        internal static string SPSFW_Err_XsltTransformation {
            get {
                return ResourceManager.GetString("SPSFW_Err_XsltTransformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In design Mode..
        /// </summary>
        internal static string SPSFW_InDesignMode {
            get {
                return ResourceManager.GetString("SPSFW_InDesignMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unavailable).
        /// </summary>
        internal static string SPSFW_UnavailableListItem {
            get {
                return ResourceManager.GetString("SPSFW_UnavailableListItem", resourceCulture);
            }
        }
    }
}
